### ISSUE TITLE
Posts pulled from database

### ISSUE THREAD

**Issue by bradlet** [bradlet/broadboards#6]
## User Story
As a user, I would like my posts to be pulled from a database so that I can view previous posts.

## Description
Posts to the main feed should be retrievable from the database, so that old posts can be viewed.

## Acceptance Criteria
- The feed consists of old and new posts, posts are not immediately forgotten.

## March 6 Update

Very close to this being a done-done!

Two main things to do before marking this issue done-done...

- [x] After loading initial threads, the page will not load any more threads if the length of the initial threads does not reach the bottom of the screen. That is because loading new threads from the database are reliant on scrolling down. A solution must be found for this issue [A]

- [x] Convert from using testing table in the database to using the final, production-ready, table [B]

**Comment by SulimanCS** [comment]
Very close to this being a done-done!

Two main things to do before marking this issue done-done...

- [ ] After loading initial threads, the page will not load any more threads if the length of the initial threads does not reach the bottom of the screen. That is because loading new threads from the database are reliant on scrolling down. A solution must be found for this issue [A]

- [ ] Convert from using testing table in the database to using the final, production-ready, table

**Comment by SulimanCS** [comment]
I will call this issue done-done, thus changing its status to 'done'. For sub-issue A, we can create a separate issue for it since it is not really related to the database operation but rather scrolling/not having a load button
